//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("thunderstruckModel", "FK_Clanci_Galerije", "Galerije", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(thunderstruckModel.Galerije), "Clanci", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(thunderstruckModel.Clanci), true)]
[assembly: EdmRelationshipAttribute("thunderstruckModel", "FK_Thumbnail_Galerije", "Galerije", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(thunderstruckModel.Galerije), "Thumbnail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(thunderstruckModel.Thumbnail), true)]
[assembly: EdmRelationshipAttribute("thunderstruckModel", "FK_Diskografije_Galerije", "Galerije", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(thunderstruckModel.Galerije), "Diskografije", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(thunderstruckModel.Diskografije), true)]

#endregion

namespace thunderstruckModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class thunderstruckEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new thunderstruckEntities object using the connection string found in the 'thunderstruckEntities' section of the application configuration file.
        /// </summary>
        public thunderstruckEntities() : base("name=thunderstruckEntities", "thunderstruckEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new thunderstruckEntities object.
        /// </summary>
        public thunderstruckEntities(string connectionString) : base(connectionString, "thunderstruckEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new thunderstruckEntities object.
        /// </summary>
        public thunderstruckEntities(EntityConnection connection) : base(connection, "thunderstruckEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Administrator> Administrator
        {
            get
            {
                if ((_Administrator == null))
                {
                    _Administrator = base.CreateObjectSet<Administrator>("Administrator");
                }
                return _Administrator;
            }
        }
        private ObjectSet<Administrator> _Administrator;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clanci> Clanci
        {
            get
            {
                if ((_Clanci == null))
                {
                    _Clanci = base.CreateObjectSet<Clanci>("Clanci");
                }
                return _Clanci;
            }
        }
        private ObjectSet<Clanci> _Clanci;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Diskografije> Diskografije
        {
            get
            {
                if ((_Diskografije == null))
                {
                    _Diskografije = base.CreateObjectSet<Diskografije>("Diskografije");
                }
                return _Diskografije;
            }
        }
        private ObjectSet<Diskografije> _Diskografije;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Galerije> Galerije
        {
            get
            {
                if ((_Galerije == null))
                {
                    _Galerije = base.CreateObjectSet<Galerije>("Galerije");
                }
                return _Galerije;
            }
        }
        private ObjectSet<Galerije> _Galerije;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Thumbnail> Thumbnail
        {
            get
            {
                if ((_Thumbnail == null))
                {
                    _Thumbnail = base.CreateObjectSet<Thumbnail>("Thumbnail");
                }
                return _Thumbnail;
            }
        }
        private ObjectSet<Thumbnail> _Thumbnail;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Administrator EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdministrator(Administrator administrator)
        {
            base.AddObject("Administrator", administrator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clanci EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClanci(Clanci clanci)
        {
            base.AddObject("Clanci", clanci);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Diskografije EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiskografije(Diskografije diskografije)
        {
            base.AddObject("Diskografije", diskografije);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Galerije EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGalerije(Galerije galerije)
        {
            base.AddObject("Galerije", galerije);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Thumbnail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThumbnail(Thumbnail thumbnail)
        {
            base.AddObject("Thumbnail", thumbnail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="thunderstruckModel", Name="Administrator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Administrator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Administrator object.
        /// </summary>
        /// <param name="administratorID">Initial value of the AdministratorID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Administrator CreateAdministrator(global::System.Int32 administratorID, global::System.String username, global::System.String password)
        {
            Administrator administrator = new Administrator();
            administrator.AdministratorID = administratorID;
            administrator.Username = username;
            administrator.Password = password;
            return administrator;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdministratorID
        {
            get
            {
                return _AdministratorID;
            }
            set
            {
                if (_AdministratorID != value)
                {
                    OnAdministratorIDChanging(value);
                    ReportPropertyChanging("AdministratorID");
                    _AdministratorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdministratorID");
                    OnAdministratorIDChanged();
                }
            }
        }
        private global::System.Int32 _AdministratorID;
        partial void OnAdministratorIDChanging(global::System.Int32 value);
        partial void OnAdministratorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="thunderstruckModel", Name="Clanci")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clanci : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clanci object.
        /// </summary>
        /// <param name="clanakID">Initial value of the ClanakID property.</param>
        /// <param name="textClanka">Initial value of the TextClanka property.</param>
        /// <param name="nazivClanka">Initial value of the NazivClanka property.</param>
        public static Clanci CreateClanci(global::System.Int32 clanakID, global::System.String textClanka, global::System.String nazivClanka)
        {
            Clanci clanci = new Clanci();
            clanci.ClanakID = clanakID;
            clanci.TextClanka = textClanka;
            clanci.NazivClanka = nazivClanka;
            return clanci;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClanakID
        {
            get
            {
                return _ClanakID;
            }
            set
            {
                if (_ClanakID != value)
                {
                    OnClanakIDChanging(value);
                    ReportPropertyChanging("ClanakID");
                    _ClanakID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClanakID");
                    OnClanakIDChanged();
                }
            }
        }
        private global::System.Int32 _ClanakID;
        partial void OnClanakIDChanging(global::System.Int32 value);
        partial void OnClanakIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TextClanka
        {
            get
            {
                return _TextClanka;
            }
            set
            {
                OnTextClankaChanging(value);
                ReportPropertyChanging("TextClanka");
                _TextClanka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TextClanka");
                OnTextClankaChanged();
            }
        }
        private global::System.String _TextClanka;
        partial void OnTextClankaChanging(global::System.String value);
        partial void OnTextClankaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NazivClanka
        {
            get
            {
                return _NazivClanka;
            }
            set
            {
                OnNazivClankaChanging(value);
                ReportPropertyChanging("NazivClanka");
                _NazivClanka = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NazivClanka");
                OnNazivClankaChanged();
            }
        }
        private global::System.String _NazivClanka;
        partial void OnNazivClankaChanging(global::System.String value);
        partial void OnNazivClankaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GalerijaID
        {
            get
            {
                return _GalerijaID;
            }
            set
            {
                OnGalerijaIDChanging(value);
                ReportPropertyChanging("GalerijaID");
                _GalerijaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GalerijaID");
                OnGalerijaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GalerijaID;
        partial void OnGalerijaIDChanging(Nullable<global::System.Int32> value);
        partial void OnGalerijaIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("thunderstruckModel", "FK_Clanci_Galerije", "Galerije")]
        public Galerije Galerije
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Clanci_Galerije", "Galerije").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Clanci_Galerije", "Galerije").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Galerije> GalerijeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Clanci_Galerije", "Galerije");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Galerije>("thunderstruckModel.FK_Clanci_Galerije", "Galerije", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="thunderstruckModel", Name="Diskografije")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Diskografije : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Diskografije object.
        /// </summary>
        /// <param name="diskografijaID">Initial value of the DiskografijaID property.</param>
        /// <param name="naziv">Initial value of the Naziv property.</param>
        /// <param name="clanak">Initial value of the Clanak property.</param>
        public static Diskografije CreateDiskografije(global::System.Int32 diskografijaID, global::System.String naziv, global::System.String clanak)
        {
            Diskografije diskografije = new Diskografije();
            diskografije.DiskografijaID = diskografijaID;
            diskografije.Naziv = naziv;
            diskografije.Clanak = clanak;
            return diskografije;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiskografijaID
        {
            get
            {
                return _DiskografijaID;
            }
            set
            {
                if (_DiskografijaID != value)
                {
                    OnDiskografijaIDChanging(value);
                    ReportPropertyChanging("DiskografijaID");
                    _DiskografijaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DiskografijaID");
                    OnDiskografijaIDChanged();
                }
            }
        }
        private global::System.Int32 _DiskografijaID;
        partial void OnDiskografijaIDChanging(global::System.Int32 value);
        partial void OnDiskografijaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naziv
        {
            get
            {
                return _Naziv;
            }
            set
            {
                OnNazivChanging(value);
                ReportPropertyChanging("Naziv");
                _Naziv = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naziv");
                OnNazivChanged();
            }
        }
        private global::System.String _Naziv;
        partial void OnNazivChanging(global::System.String value);
        partial void OnNazivChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Clanak
        {
            get
            {
                return _Clanak;
            }
            set
            {
                OnClanakChanging(value);
                ReportPropertyChanging("Clanak");
                _Clanak = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Clanak");
                OnClanakChanged();
            }
        }
        private global::System.String _Clanak;
        partial void OnClanakChanging(global::System.String value);
        partial void OnClanakChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GalerijaID
        {
            get
            {
                return _GalerijaID;
            }
            set
            {
                OnGalerijaIDChanging(value);
                ReportPropertyChanging("GalerijaID");
                _GalerijaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GalerijaID");
                OnGalerijaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GalerijaID;
        partial void OnGalerijaIDChanging(Nullable<global::System.Int32> value);
        partial void OnGalerijaIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("thunderstruckModel", "FK_Diskografije_Galerije", "Galerije")]
        public Galerije Galerije
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Diskografije_Galerije", "Galerije").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Diskografije_Galerije", "Galerije").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Galerije> GalerijeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Diskografije_Galerije", "Galerije");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Galerije>("thunderstruckModel.FK_Diskografije_Galerije", "Galerije", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="thunderstruckModel", Name="Galerije")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Galerije : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Galerije object.
        /// </summary>
        /// <param name="galerijaID">Initial value of the GalerijaID property.</param>
        /// <param name="nazivGalerije">Initial value of the NazivGalerije property.</param>
        public static Galerije CreateGalerije(global::System.Int32 galerijaID, global::System.String nazivGalerije)
        {
            Galerije galerije = new Galerije();
            galerije.GalerijaID = galerijaID;
            galerije.NazivGalerije = nazivGalerije;
            return galerije;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GalerijaID
        {
            get
            {
                return _GalerijaID;
            }
            set
            {
                if (_GalerijaID != value)
                {
                    OnGalerijaIDChanging(value);
                    ReportPropertyChanging("GalerijaID");
                    _GalerijaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GalerijaID");
                    OnGalerijaIDChanged();
                }
            }
        }
        private global::System.Int32 _GalerijaID;
        partial void OnGalerijaIDChanging(global::System.Int32 value);
        partial void OnGalerijaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NazivGalerije
        {
            get
            {
                return _NazivGalerije;
            }
            set
            {
                OnNazivGalerijeChanging(value);
                ReportPropertyChanging("NazivGalerije");
                _NazivGalerije = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NazivGalerije");
                OnNazivGalerijeChanged();
            }
        }
        private global::System.String _NazivGalerije;
        partial void OnNazivGalerijeChanging(global::System.String value);
        partial void OnNazivGalerijeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("thunderstruckModel", "FK_Clanci_Galerije", "Clanci")]
        public EntityCollection<Clanci> Clanci
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Clanci>("thunderstruckModel.FK_Clanci_Galerije", "Clanci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Clanci>("thunderstruckModel.FK_Clanci_Galerije", "Clanci", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("thunderstruckModel", "FK_Thumbnail_Galerije", "Thumbnail")]
        public EntityCollection<Thumbnail> Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Thumbnail>("thunderstruckModel.FK_Thumbnail_Galerije", "Thumbnail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Thumbnail>("thunderstruckModel.FK_Thumbnail_Galerije", "Thumbnail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("thunderstruckModel", "FK_Diskografije_Galerije", "Diskografije")]
        public EntityCollection<Diskografije> Diskografije
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Diskografije>("thunderstruckModel.FK_Diskografije_Galerije", "Diskografije");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Diskografije>("thunderstruckModel.FK_Diskografije_Galerije", "Diskografije", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="thunderstruckModel", Name="Thumbnail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Thumbnail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Thumbnail object.
        /// </summary>
        /// <param name="thumbnailID">Initial value of the ThumbnailID property.</param>
        /// <param name="nazivThumbnaila">Initial value of the NazivThumbnaila property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        /// <param name="galerijaID">Initial value of the GalerijaID property.</param>
        public static Thumbnail CreateThumbnail(global::System.Int32 thumbnailID, global::System.String nazivThumbnaila, global::System.String link, global::System.Int32 galerijaID)
        {
            Thumbnail thumbnail = new Thumbnail();
            thumbnail.ThumbnailID = thumbnailID;
            thumbnail.NazivThumbnaila = nazivThumbnaila;
            thumbnail.Link = link;
            thumbnail.GalerijaID = galerijaID;
            return thumbnail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ThumbnailID
        {
            get
            {
                return _ThumbnailID;
            }
            set
            {
                if (_ThumbnailID != value)
                {
                    OnThumbnailIDChanging(value);
                    ReportPropertyChanging("ThumbnailID");
                    _ThumbnailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ThumbnailID");
                    OnThumbnailIDChanged();
                }
            }
        }
        private global::System.Int32 _ThumbnailID;
        partial void OnThumbnailIDChanging(global::System.Int32 value);
        partial void OnThumbnailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NazivThumbnaila
        {
            get
            {
                return _NazivThumbnaila;
            }
            set
            {
                OnNazivThumbnailaChanging(value);
                ReportPropertyChanging("NazivThumbnaila");
                _NazivThumbnaila = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NazivThumbnaila");
                OnNazivThumbnailaChanged();
            }
        }
        private global::System.String _NazivThumbnaila;
        partial void OnNazivThumbnailaChanging(global::System.String value);
        partial void OnNazivThumbnailaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkNaVelikuSliku
        {
            get
            {
                return _LinkNaVelikuSliku;
            }
            set
            {
                OnLinkNaVelikuSlikuChanging(value);
                ReportPropertyChanging("LinkNaVelikuSliku");
                _LinkNaVelikuSliku = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkNaVelikuSliku");
                OnLinkNaVelikuSlikuChanged();
            }
        }
        private global::System.String _LinkNaVelikuSliku;
        partial void OnLinkNaVelikuSlikuChanging(global::System.String value);
        partial void OnLinkNaVelikuSlikuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sirina
        {
            get
            {
                return _Sirina;
            }
            set
            {
                OnSirinaChanging(value);
                ReportPropertyChanging("Sirina");
                _Sirina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sirina");
                OnSirinaChanged();
            }
        }
        private Nullable<global::System.Int32> _Sirina;
        partial void OnSirinaChanging(Nullable<global::System.Int32> value);
        partial void OnSirinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Visina
        {
            get
            {
                return _Visina;
            }
            set
            {
                OnVisinaChanging(value);
                ReportPropertyChanging("Visina");
                _Visina = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visina");
                OnVisinaChanged();
            }
        }
        private Nullable<global::System.Int32> _Visina;
        partial void OnVisinaChanging(Nullable<global::System.Int32> value);
        partial void OnVisinaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DodatniHtml
        {
            get
            {
                return _DodatniHtml;
            }
            set
            {
                OnDodatniHtmlChanging(value);
                ReportPropertyChanging("DodatniHtml");
                _DodatniHtml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DodatniHtml");
                OnDodatniHtmlChanged();
            }
        }
        private global::System.String _DodatniHtml;
        partial void OnDodatniHtmlChanging(global::System.String value);
        partial void OnDodatniHtmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GalerijaID
        {
            get
            {
                return _GalerijaID;
            }
            set
            {
                OnGalerijaIDChanging(value);
                ReportPropertyChanging("GalerijaID");
                _GalerijaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GalerijaID");
                OnGalerijaIDChanged();
            }
        }
        private global::System.Int32 _GalerijaID;
        partial void OnGalerijaIDChanging(global::System.Int32 value);
        partial void OnGalerijaIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("thunderstruckModel", "FK_Thumbnail_Galerije", "Galerije")]
        public Galerije Galerije
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Thumbnail_Galerije", "Galerije").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Thumbnail_Galerije", "Galerije").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Galerije> GalerijeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galerije>("thunderstruckModel.FK_Thumbnail_Galerije", "Galerije");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Galerije>("thunderstruckModel.FK_Thumbnail_Galerije", "Galerije", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
